[workspace]
members = [
    "core",
    "cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Jose Flores"]
description = "AI-powered task complexity analyzer"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3 